#!/bin/bash
source "$(dirname $0)/common.sh"

dir="$BACKUP_TARGET/projects"
rm -fr "$dir"
mkdir -p "$dir"
cd $dir

for p in $(oc get projects --no-headers -o custom-columns=name:.metadata.name); do
 /root/backup/project-export.sh $p
done
